### PR TITLE
Add departure and arrival to routing api

### PR DESCRIPTION
**Pull request by eifinger**

### CODE REVIEW

**Comment by eifinger** [comment]
No idea, why that one check fails.

**Comment by eifinger** [comment]
If this gets merged, can you release a new version? =)

**Comment by abdullahselek** [comment]
@eifinger thanks for your contribution 👍 I'm going to release a new patch today.

**Comment by abdullahselek** [comment]
Also I checked on [https://developer.here.com/documentation](https://developer.here.com/documentation) some API endpoints has changed. And I'm planing to update them if you have time could you please help me to verify changes that I will do are still ok?

**Comment by eifinger** [comment]
Would be happy to do so. Feel free to "@" me

**Comment by abdullahselek** [comment]
Awesome thanks.

**Comment by abdullahselek** [comment]
Just released new version `0.6.3.4`.

**Pull request merged**
