### PR TITLE
Fix error handling for new unauthorized responses

### PR DESCRIPTION
**Pull request by eifinger**
Some of the apis changed their response when the apiKey is wrong or not supplied.
This PR fixes the error handling for the changed responses.

### CODE REVIEW

**Review by abdullahselek — APPROVED** [review]
All looks good to me!

**Comment by abdullahselek** [comment]
Thanks for your PR @eifinger!

**Comment by abdullahselek** [comment]
I just released a new patch which I think might be useful for you.

**Comment by eifinger** [comment]
Thank you!

**Pull request merged**
