### PR TITLE
Added reverse geocoding and rme api.

### PR DESCRIPTION
**Pull request by aykutkilic**
I've added reverse geocoding and RME api.

### CODE REVIEW

**Comment by abdullahselek** [comment]
Hi @aykutkilic thanks for your contribution. I had a quick look and it looks like you have forgotten new model classes in `models.py` please add them into your pull request.

**Comment by aykutkilic** [comment]
I've added the missing files. Now it should be ok.

**Comment by abdullahselek** [comment]
Just failing for `Python 2.7` you can use `io.open` instead of `open` like `with io.open('testdata/models/public_transit_api_nearby.json', 'r', encoding='utf-8') as f:`.

**Comment by aykutkilic** [comment]
It's already 5 commits. When merging I guess they should somehow be squashed.

**Comment by aykutkilic** [comment]
Do you have any idea why we get: "UnicodeEncodeError: 'ascii' codec can't encode character u'\xa9' in position 775: ordinal not in range(128)" in Python 2.7?

**Comment by abdullahselek** [comment]
Yes we can squash commits and to your question try encoding `content` with `utf-8` on your `get_zipped_base64` method. You can run all tests on your machine before pushing.

**Comment by aykutkilic** [comment]
I run the tests and also tox they pass but fail in the build server.

**Comment by abdullahselek** [comment]
You are right same on my side could you please try that `content_bytes = content.encode('utf-8')` on `get_zipped_base64`.

**Comment by abdullahselek** [comment]
Just to let you know adding `utf-8` parameter worked on `Python 2.7` you can have a look at my branch `pr-3`.

**Comment by abdullahselek** [comment]
I guess it's time to squash your commits and than we can merge.

**Pull request merged**
