### PR TITLE
Start using new endpoints.

### PR DESCRIPTION
**Pull request by abdullahselek**
- There is some inconsistency on the use of `apiKey`, sometimes we
have to use `apiKey` sometimes `apikey`.
- As I checked for most of the endpoints responses are same.

### CODE REVIEW

**Comment by abdullahselek** [comment]
@eifinger please have a look when you have time.

**Comment by eifinger** [comment]
I will have a look tomorrow.
As far as I read the release notes from HERE it could be that we have to support app_code for legacy reasons.

**Comment by eifinger** [comment]
Looks good to me.

I thought about whether to keep the `app_id` `app_code` functionality in order to not introduce a breaking change for existing users. But as far as I understand the API documentation they plan to remove it completely in the future. So we might as well get rid of it now.

**Comment by abdullahselek** [comment]
Thanks @eifinger I'm gonna merge and release a new version.

**Pull request merged**
